config/routes.rb
Rails.application.routes.draw do
  resources :speedruns
  root 'pages#home'
  resources :categories
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  validates_uniqueness_of :name
  has_one_attached :image, dependent: :destroy

  def thumbnail
    return image.variant(resize_to_limit: [200, 200]).processed if image.attached?
  end
end

app/models/speedrun.rb
class Speedrun < ApplicationRecord
  belongs_to :user
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: %i[ index show ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category), notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name, :image)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/speedruns_controller.rb
class SpeedrunsController < ApplicationController
  before_action :set_speedrun, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[index show]

  # GET /speedruns or /speedruns.json
  def index
    @speedruns = Speedrun.all
  end

  # GET /speedruns/1 or /speedruns/1.json
  def show; end

  # GET /speedruns/new
  def new
    @speedrun = Speedrun.new
  end

  # GET /speedruns/1/edit
  def edit; end

  # POST /speedruns or /speedruns.json
  def create
    @speedrun = Speedrun.new(speedrun_params)
    @speedrun.user = current_user

    respond_to do |format|
      if @speedrun.save
        format.html { redirect_to speedrun_url(@speedrun), notice: 'Speedrun was successfully created.' }
        format.json { render :show, status: :created, location: @speedrun }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @speedrun.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /speedruns/1 or /speedruns/1.json
  def update
    respond_to do |format|
      if @speedrun.update(speedrun_params)
        format.html { redirect_to speedrun_url(@speedrun), notice: 'Speedrun was successfully updated.' }
        format.json { render :show, status: :ok, location: @speedrun }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @speedrun.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /speedruns/1 or /speedruns/1.json
  def destroy
    @speedrun.destroy

    respond_to do |format|
      format.html { redirect_to speedruns_url, notice: 'Speedrun was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_speedrun
    @speedrun = Speedrun.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def speedrun_params
    params.require(:speedrun).permit(:category_id, :time)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/speedruns_helper.rb
module SpeedrunsHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <p>
    <strong>Name:</strong>
    <%= category.name %>
  </p>
  <%= image_tag(category.thumbnail) if category.image.attached? %>
</div>

app/views/categories/_form.html.erb
<%= simple_form_for(@category) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :image%>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<div class="container">
<p style="color: green"><%= notice %></p>

<h1>Categories</h1>

<div id="categories">
  <% @categories.each do |category| %>
    <%= render category %>
    <p>
      <%= link_to "Show this category", category %>
    </p>
  <% end %>
</div>

<%= link_to "New category", new_category_path %>
</div>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @category %>

<div>
  <%= link_to "Edit this category", edit_category_path(@category) %> |
  <%= link_to "Back to categories", categories_path %>

  <%= button_to "Destroy this category", @category, method: :delete %>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "Speedruns", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Home", root_path, class:"nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to "Categories", categories_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Speedruns", speedruns_path, class: "nav-link" %>
        </li>
      </ul>
      <ul class="navbar-nav mr-auto mb-2 mb-lg-0">
        <% if current_user %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <%= current_user.email %>
            </a>
            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <li><%= link_to "Create Category", new_category_path, class:"dropdown-item" %></li>
              <li><%= link_to "New Speedrun", "#", class:"dropdown-item" %></li>
              <li><hr class="dropdown-divider"></li>
              <li><%= button_to "Logout", destroy_user_session_path, class:"dropdown-item", method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Create Account", new_user_registration_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class:"nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Video</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </head>
  <body>
    <%= render "layouts/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/speedruns/_form.html.erb
<%= simple_form_for(@speedrun) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  <div class="form-inputs">
    <%= f.association :category %>
    <%= f.input :time %>
  </div>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/speedruns/_speedrun.html.erb
<div id="<%= dom_id speedrun %>">
  <p>
    <strong>User:</strong>
    <%= speedrun.user.email %>
  </p>
  <p>
    <strong>Category:</strong>
    <%= speedrun.category.name %>
  </p>
  <p>
    <strong>Time:</strong>
    <%= speedrun.time %>
  </p>
</div>

app/views/speedruns/edit.html.erb
<h1>Editing speedrun</h1>

<%= render "form", speedrun: @speedrun %>

<br>

<div>
  <%= link_to "Show this speedrun", @speedrun %> |
  <%= link_to "Back to speedruns", speedruns_path %>
</div>

app/views/speedruns/index.html.erb
<div class="container">
  <p style="color: green"><%= notice %></p>
  <h1>Speedruns</h1>
  <div id="speedruns">
    <% @speedruns.each do |speedrun| %>
      <%= render speedrun %>
      <p>
        <%= link_to "Show this speedrun", speedrun %>
      </p>
    <% end %>
  </div>
  <%= link_to "New speedrun", new_speedrun_path %>
</div>

app/views/speedruns/new.html.erb
<h1>New speedrun</h1>

<%= render "form", speedrun: @speedrun %>

<br>

<div>
  <%= link_to "Back to speedruns", speedruns_path %>
</div>

app/views/speedruns/show.html.erb
<div class="container">
  <p style="color: green"><%= notice %></p>
  <%= render @speedrun %>
  <div>
    <%= link_to "Edit this speedrun", edit_speedrun_path(@speedrun) %> |
    <%= link_to "Back to speedruns", speedruns_path %>
    <%= button_to "Destroy this speedrun", @speedrun, method: :delete %>
  </div>
</div>